### PR TITLE
Option for meteor settings file

### PR DESCRIPTION
**Pull request by eldog**
Some applications use a settings file, given via the `--settings` argument to the
`meteor`/`mrt` command or as a JSON string assigned to the `METEOR_SETTINGS`
environmental variable on self-hosted environments.

By providing an argument to --settings it is now possible to provide the
location of the meteor settings file and this is read, stringified and assigned
to the `METEOR_SETTINGS` environmental variable for each app.

Example usage

```
laika --settings settings.json
```

Note: if you're wondering about the white-space changes and new line, my vim does that automatically, I hope you don't mind.

### CODE REVIEW

**Comment by arunoda** [comment]
Cool. Thanks. I'll merge this.

**Comment by arunoda** [comment]
Published as `0.2.25`

**Comment by datacarl** [comment]
I get an error using settings (my settings.json is at the top of the app dir and I run laika from there):

laika --settings settings.json

  injecting laika...
  loading phantomjs...
  loading initial app pool...
  cleaning up injected code

module.js:340
    throw err;
          ^
Error: Cannot find module 'settings.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at App.start (/usr/local/share/npm/lib/node_modules/laika/lib/app.js:36:52)
    at createApp (/usr/local/share/npm/lib/node_modules/laika/lib/app_pool.js:41:9)
    at createInitialPool [as _onTimeout](/usr/local/share/npm/lib/node_modules/laika/lib/app_pool.js:28:7)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by arunoda** [comment]
Yes. This seems to be an error.
For now try `./settings`

**Comment by arunoda** [comment]
Try new version `0.2.26`

**Comment by datacarl** [comment]
./settings didnt help. Works with 0.2.26. Thanks!
