### PR TITLE
Fixes #140

### LINKED ISSUE #140: Cannot file module .meteor/release/METEOR@0.9.1.release.json
I'm following this [this tutorial](http://mherman.org/blog/2014/01/29/meteor-dot-js-in-action-create-an-app-test-with-laika/#.VAmrrmSSzKg) and when I try to run Laika test I get the output bellow.

I'm new to meteor and Laika so I might configure something wrong.

```
  injecting laika...
  loading phantomjs...
  loading initial app pool...
  cleaning up injected code


module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/me/.meteor/releases/METEOR@0.9.1.release.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.getMeteorToolsPath (/usr/local/lib/node_modules/laika/lib/helpers.js:33:18)
    at Object.getMeteorNode (/usr/local/lib/node_modules/laika/lib/helpers.js:43:35)
    at Object.getMeteoriteNode (/usr/local/lib/node_modules/laika/lib/helpers.js:59:20)
    at detectConfig (/usr/local/lib/node_modules/laika/lib/app_pool.js:83:35)
    at new AppPool (/usr/local/lib/node_modules/laika/lib/app_pool.js:16:19)
    at /usr/local/lib/node_modules/laika/bin/_laika:90:17
```

### PR DESCRIPTION
**Pull request by apendua**
The easiest possible fix to make laika work with Meteor 0.9.x.

@arunoda This is urgent man :)

### CODE REVIEW

**Comment by arunoda** [comment]
Hey, thanks.
I'll do a release.

BTW: Are you looking to manage laika?
I'm having issues with the time allocation for laika.

**Comment by apendua** [comment]
@arunoda Cool, why not ... I have implemented a lot of updates to make laika work with my projects, so I am pretty much involved already.

**Comment by arunoda** [comment]
Awesome. I'll add you as the maintainer to the npm and this repo :)
So you can make releases :)

send me your npm username.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
